### PR TITLE
fix: show some stats even if the user not logged in

### LINKED ISSUE #137: Show stats even the user is not signed in

### PR DESCRIPTION
**Pull request by JustinCast**
# PR title goes here
_Show some stats even if the user is not logged in_
## How should this be tested?
1. `yarn start`
## Notes or observations
_no observations for this PR_
## Linked issues
closes #137

### CODE REVIEW

File: src/utils/EthDataProvider/EthDataProvider.js [hunk 1]
```diff
@@ -66,6 +66,22 @@ const earned = async wallet => {
   return 0;
 };
 
+const defaultAPR = async () => {
```
Comment (kesar) [inline src/utils/EthDataProvider/EthDataProvider.js:69]: example to query blockchain if user has no wallet connected

File: src/features/Lock/stats.js [hunk 2]
```diff
@@ -137,19 +139,25 @@ const Stats = ({ wallet, lockedAlready }) => {
       const { tvl, lockedByUser, hiIQSupply, rewardsAcrossLockPeriod } =
         await getStats(wallet);
 
+      const aprDefault = await defaultAPR(); // TODO: move to right place (user is not logged). example to get APR without wallet connected: use value for base APR (rename to just APR)
+      console.log(aprDefault);
+
       const yearsLock = 4; // assuming a 4 year lock
 
-      const rewardsBasedOnLockPeriod = lockedByUser * (1 + 0.75 * yearsLock);
+      const amountLocked = lockedByUser > 0 ? lockedByUser : 100000;
```
Comment (kesar) [inline src/features/Lock/stats.js:147]: this allows to show APR to users that have no hiiq

File: src/utils/EthDataProvider/EthDataProvider.js (hunk 1 above)
Comment (kesar) [reply src/utils/EthDataProvider/EthDataProvider.js:69]: the remaining task are the TODOs: get APR for unlogged users using this method

File: src/features/Lock/stats.js (hunk 2 above)
Comment (kesar) [reply src/features/Lock/stats.js:147]: I would suggest to try to refactor all the APR part into his own scoped function because its adding too much complexity to the Stats function (and it will increase with the APR for unlogged users)

**Comment by kesar** [comment]
looking great 👍🏻
