### PR TITLE
fix: infocard-not-showing-increasing-amount

### LINKED ISSUE #146: Increase amount does not show the card w info
image

missing card with how many tokens i will have

### PR DESCRIPTION
**Pull request by JustinCast**
# PR title goes here
_Info card data now includes current + new input iq amount, when increasing it_
## How should this be tested?
1. `yarn start`
## Notes or observations
_jot down something here_
## Linked issues
closes #146

### CODE REVIEW

**Review by kesar — APPROVED** [review]

**Review by kesar — CHANGES_REQUESTED** [review]
image

adding 44 IQ i wont get 6M of HIIQ

File: src/features/Lock/lock.js [hunk 1]
```diff
@@ -435,8 +447,19 @@ const Lock = () => {
                 />
               ) : null}
 
+              {lockEnd && filledAmount && diffDays ? (
+                <InfoSwapCard
+                  timeLockedDescription="Current unlock time (days)"
+                  balanceDescription="Expected hiIQ (includes current)"
+                  tokensLocked={Number(currentHiIQ) + Number(filledAmount)}
```
Comment (kesar) [inline src/features/Lock/lock.js:454]: its not currentHiIQ, I think its the current IQ tokens locked

**Review by kesar — APPROVED** [review]
