### PR TITLE
Fix/#97

### LINKED ISSUE #97: Reduce code duplicity
Files
- [ ] EthDataProvider: create a context to check the wallet status instead of compare in each method

### PR DESCRIPTION
**Pull request by JustinCast**
# Reduce code duplicity
_Some code at EthDataProvider was reused to enable clarity_
## How should this be tested?
1. `yarn start`
## Notes or observations
_no observations_
## Linked issues
closes #97

### CODE REVIEW

**Review by kesar — APPROVED** [review]

File: src/utils/EthDataProvider/EthDataProvider.js [hunk 1]
```diff
@@ -172,21 +177,17 @@ const reverseIQtoEOSTx = async (amount, wallet, eosAccount) => {
   const amountParsed = ethers.utils.parseEther(amount).toString();
   if (wallet.status === "connected") {
     const provider = new ethers.providers.Web3Provider(wallet.ethereum);
-    const erc20 = new ethers.Contract(
-      iqAddress,
-      erc20Abi,
-      provider.getSigner()
-    );
+
+    const erc20 = getERC20IQContract(wallet);
```
Comment (kesar) [inline src/utils/EthDataProvider/EthDataProvider.js:181]: this was wrong. Please make sure you test what you refactor. Bridge ETH -> EOS was broken
