### PR TITLE
fix: lock related fixes

### LINKED ISSUE #153: Rounding error when increasing unlock time to max

### PR DESCRIPTION
**Pull request by JustinCast**
# Lock related fixes
- Correctly call button disabled validation
- Prevent rounding error when set max available lock time
## How should this be tested?
1. `yarn start`

## Notes or observations
Test report: https://docs.google.com/spreadsheets/d/1GuZNrp8Iwm_72bYQ0sBScVCtt5fMW3UrMZXPZY4TWVY/edit?usp=sharing
## Linked issues
closes #153 #155

### CODE REVIEW

File: src/utils/EthDataProvider/EthDataProvider.js [hunk 1]
```diff
@@ -314,7 +314,7 @@ const getMaximumLockableTime = async (wallet, lockEnd) => {
     const diffTime = Math.abs(max - lockEnd);
     const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24));
 
-    return diffDays - 1;
+    return diffDays - 4;
```
Comment (kesar) [inline src/utils/EthDataProvider/EthDataProvider.js:317]: why 4?

File: src/features/Lock/lock.js [hunk 2]
```diff
@@ -411,7 +418,7 @@ const Lock = () => {
                         </Button>
                       ) : (
                         <Button
-                          disabled={buttonIsDisabled}
+                          disabled={buttonIsDisabled()}
```
Comment (kesar) [inline src/features/Lock/lock.js:421]: wasn't this working without making it a explicit call?

Comment (JustinCast) [reply src/features/Lock/lock.js:423]: It wasn't

File: src/utils/EthDataProvider/EthDataProvider.js (hunk 1 above)
Comment (JustinCast) [reply src/utils/EthDataProvider/EthDataProvider.js]: Just leave it as it was

**Comment by JustinCast** [comment]
@kesar feel free to review this PR

File: src/components/ui/swapContainer.js [hunk 3]
```diff
@@ -178,6 +178,7 @@ const SwapContainer = ({
   const handleOnInputChange = event => {
     let { value } = event.target;
     value = Number(value);
+    value = Number(value.toString().match(/^-?\d+(?:\.\d{0,2})?/)[0]);
```
Comment (kesar) [inline src/components/ui/swapContainer.js:181]: are the numbers being formatted based on user intl ? because this can be a problem if users uses , instead of . to separate decimals and so on.

perhaps there is a better way to do this without assuming that regexp is gonna work

Comment (JustinCast) [reply src/components/ui/swapContainer.js:181]: Searching an alternative...

Comment (kesar) [reply src/components/ui/swapContainer.js:181]: I was thinking you could use parseFloat(xx).toFixed(2) but doing the parseFloat you are gonna hit the same rounding issue

Comment (JustinCast) [reply src/components/ui/swapContainer.js:181]: Yep. Using .toFixed() will lead us to the same issue. I played around with it

Comment (JustinCast) [reply src/components/ui/swapContainer.js]: @kesar I think the issue is solved
